import { Tool } from './types';
import { MergePdf, SplitPdf, CompressPdf, RotatePdf, AddPageNumbersPdf, OcrPdf, PdfToWord, ProtectPdf, ImageToPdf, PdfToImage, ExtractText, AddWatermarkPdf, QrCodeGenerator } from './tools';
import { DocumentDuplicateIcon, ArrowsRightLeftIcon, ArchiveBoxArrowDownIcon, ArrowPathIcon, ListBulletIcon, MagnifyingGlassIcon, DocumentTextIcon, ShieldCheckIcon, PhotoIcon, RectangleStackIcon, DocumentMinusIcon, TagIcon, QrCodeIcon } from './components/icons';

export const tools: Tool[] = [
    {
        id: 'merge',
        title: 'دمج PDF',
        description: 'اجمع عدة ملفات PDF في ملف واحد منظم وسهل المشاركة.',
        icon: DocumentDuplicateIcon,
        component: MergePdf,
        category: 'organize',
        categoryLabel: 'تنظيم المستندات',
        colorTheme: 'sky',
        badge: 'الأكثر استخداماً'
    },
    {
        id: 'split',
        title: 'تقسيم PDF',
        description: 'قسّم عدة ملفات PDF دفعة واحدة واستخرج صفحاتها مع إمكانية التحميل المفرد.',
        icon: ArrowsRightLeftIcon,
        component: SplitPdf,
        category: 'organize',
        categoryLabel: 'تنظيم المستندات',
        colorTheme: 'sky',
        badge: 'دعم عدة ملفات'
    },
    {
        id: 'compress',
        title: 'ضغط PDF',
        description: 'قلل حجم عدة ملفات PDF دفعة واحدة مع خيار التنزيل المفرد لكل ملف.',
        icon: ArchiveBoxArrowDownIcon,
        component: CompressPdf,
        category: 'convert',
        categoryLabel: 'تحسين الحجم',
        colorTheme: 'emerald',
        badge: 'دعم عدة ملفات'
    },
    {
        id: 'rotate',
        title: 'تدوير PDF',
        description: 'أدر صفحات ملف PDF الخاص بك 90 أو 180 أو 270 درجة بنقرة واحدة.',
        icon: ArrowPathIcon,
        component: RotatePdf,
        category: 'organize',
        categoryLabel: 'تنظيم المستندات',
        colorTheme: 'sky',
    },
    {
        id: 'image-to-pdf',
        title: 'تحويل الصور إلى PDF',
        description: 'اجمع مجموعة صور بتنسيق JPG أو PNG وحوّلها إلى ملف PDF عالي الدقة.',
        icon: PhotoIcon,
        component: ImageToPdf,
        category: 'convert',
        categoryLabel: 'تحويل وتصدير',
        colorTheme: 'indigo',
    },
    {
        id: 'pdf-to-image',
        title: 'تحويل PDF إلى صور',
        description: 'استخرج كل صفحة من ملف PDF كصورة منفصلة بجودة فائقة.',
        icon: RectangleStackIcon,
        component: PdfToImage,
        category: 'convert',
        categoryLabel: 'تحويل وتصدير',
        colorTheme: 'indigo',
    },
    {
        id: 'pdf-to-word',
        title: 'تحويل PDF إلى Word',
        description: 'حوّل ملف PDF إلى مستند Word قابل للتعديل المباشر وبسرعة فائقة.',
        icon: DocumentTextIcon,
        component: PdfToWord,
        category: 'convert',
        categoryLabel: 'تحويل وتصدير',
        colorTheme: 'indigo',
        badge: 'سريع ومحلي'
    },
    {
        id: 'add-page-numbers',
        title: 'ترقيم الصفحات',
        description: 'أضف أرقام الصفحات بتنسيق وموضع مخصصين بكل سهولة واحترافية.',
        icon: ListBulletIcon,
        component: AddPageNumbersPdf,
        category: 'organize',
        categoryLabel: 'تنظيم المستندات',
        colorTheme: 'sky',
    },
    {
        id: 'watermark',
        title: 'إضافة علامة مائية',
        description: 'أضف نصوصاً أو شعارات شفافة لحماية حقوق الملكية لمستنداتك.',
        icon: TagIcon,
        component: AddWatermarkPdf,
        category: 'security',
        categoryLabel: 'أمان وحماية',
        colorTheme: 'rose',
    },
    {
        id: 'protect',
        title: 'حماية وتعتيم PDF',
        description: 'قم بإخفاء وتعتيم البيانات الحساسة داخل مستند PDF بشكل دائم.',
        icon: ShieldCheckIcon,
        component: ProtectPdf,
        category: 'security',
        categoryLabel: 'أمان وحماية',
        colorTheme: 'rose',
        badge: 'حماية خصوصية'
    },
    {
        id: 'extract-text',
        title: 'استخراج النصوص',
        description: 'استخرج كل النصوص المكتوبة من ملف PDF مع إمكانية النسخ المباشر.',
        icon: DocumentMinusIcon,
        component: ExtractText,
        category: 'extract',
        categoryLabel: 'قراءة واستخراج',
        colorTheme: 'amber',
    },
    {
        id: 'ocr',
        title: 'التعرف الضوئي (OCR)',
        description: 'حوّل المستندات المصورة والممسوحة ضوئياً إلى نصوص قابلة للبحث والنسخ.',
        icon: MagnifyingGlassIcon,
        component: OcrPdf,
        category: 'extract',
        categoryLabel: 'قراءة واستخراج',
        colorTheme: 'amber',
        badge: 'دعم العربية'
    },
    {
        id: 'qr-generator',
        title: 'إنشاء كيو آر كود (QR Code)',
        description: 'أنشئ باركود QR مخصص للروابط والواي فاي والواتساب، مع خيار دمجه في مستندات PDF أو طباعته.',
        icon: QrCodeIcon,
        component: QrCodeGenerator,
        category: 'convert',
        categoryLabel: 'إنشاء ورموز',
        colorTheme: 'violet',
        badge: 'جديد ومميز'
    },
];
